### ISSUE TITLE
about results in cifar10

### ISSUE THREAD

**Issue by 13015517713** [pprp/ofa-cifar#1]
Nice work !!!
Did you train the supernet on cifar10 and retrain the subnet? Can you share the experiment results? Thanks really.

**Comment by pprp** [comment]
Thank you for your attention. 

In fact, there are two approaches to implement ofa on cifar10/100 dataset. 
1. We don't change the network and resize the cifar image from 32 to 224.
2. We change the network inputs resolution to 32 and modify corresponding parameters to make it work. 

I adopt the second way to make it runnable but haven't trained the supernet or retrained the subnet. Here is a more reliable repo [hyperbox](https://github.com/marsggbo/hyperbox/blob/master/hyperbox/networks/ofa/ofa_mbv3.py) that might help you.
